[project]
authors = ["Cornelius Roemer <cornelius.roemer@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "mpxv-lapis-lineage-tree"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13"
git = "2.47"
gitpython = ">=3.1.43,<4"
ipykernel = ">=6.29.5,<7"
pyyaml = ">=6.0.2,<7"


