name: Run GitHub Issue Scraper
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Run every 3 hours
    - cron: "0 */3 * * *"
jobs:
  issue-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.37.0
          cache: true
      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update lineage tree"
          file_pattern: "lineage_dag.yaml"
          skip_dirty_check: false
